# Generated by Django 5.1.6 on 2025-03-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
