# Generated by Django 5.1.6 on 2025-03-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_product_description_product_description1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description1',
            new_name='description',
        ),
    ]
